In [1]:
import pandas as pd

## Load data from dane (xls)

In [2]:
path = "ProyeccionMunicipios2005_2020.xls"
sheetName = "Mpios"

### Note that the first 8 rows of the document are not necessarily, it is clean data process.

In [3]:
df = pd.read_excel(path, sheet_name=sheetName, skiprows=8)

In [4]:
df.head()

,DP,DPNOM,DPMP,MPIO,2005,2006,2007,2008,2009,2010,...,2011.2,2012.2,2013.2,2014.2,2015.2,2016.2,2017.2,2018.2,2019.2,2020.2
0,05,Antioquia,5001.0,Medellín,2214494.0,2239003.0,2265244.0,2291378.0,2317336.0,2343049.0,...,32714.0,31877.0,31092.0,30358.0,29675.0,29043.0,28462.0,27933.0,27456.0,27029.0
1,05,Antioquia,5002.0,Abejorral,20249.0,20113.0,20022.0,19930.0,19853.0,19750.0,...,13179.0,13030.0,12891.0,12746.0,12609.0,12471.0,12331.0,12189.0,12047.0,11914.0
2,05,Antioquia,5004.0,Abriaquí,2690.0,2636.0,2570.0,2504.0,2458.0,2397.0,...,1536.0,1502.0,1455.0,1411.0,1377.0,1337.0,1295.0,1261.0,1223.0,1190.0
3,05,Antioquia,5021.0,Alejandría,3816.0,3789.0,3747.0,3724.0,3688.0,3652.0,...,1781.0,1745.0,1726.0,1684.0,1654.0,1627.0,1589.0,1560.0,1508.0,1481.0
4,05,Antioquia,5030.0,Amagá,27155.0,27455.0,27709.0,27950.0,28192.0,28433.0,...,12837.0,12821.0,12805.0,12799.0,12798.0,12797.0,12806.0,12811.0,12825.0,12831.0

### get the specific municipality data

In [5]:
gramalote_row = df.loc[df['MPIO'] == 'Gramalote']

In [6]:
gramalote_row.head()

,DP,DPNOM,DPMP,MPIO,2005,2006,2007,2008,2009,2010,...,2011.2,2012.2,2013.2,2014.2,2015.2,2016.2,2017.2,2018.2,2019.2,2020.2
794,54,Norte de Santander,54313.0,Gramalote,6329.0,6231.0,6159.0,6067.0,6002.0,5928.0,...,3004.0,2953.0,2904.0,2874.0,2819.0,2793.0,2753.0,2712.0,2675.0,2648.0

### Convert to efficient file manipulation

In [7]:
# Save the row to a pickle file
gramalote_row.to_pickle("gramalote_row.pkl", compression="gzip")